# Generated by Django 3.2.7 on 2021-09-02 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey_app.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('checkbox', 'Multi choice'), ('date', 'Date'), ('email', 'Email'), ('file', 'File'), ('number', 'Number'), ('radio', 'Radio select'), ('text', 'Single line answer'), ('time', 'Time'), ('url', 'Url'), ('week', 'Week'), ('select', 'Dropdown'), ('textarea', 'Text')], max_length=10, null=True)),
                ('options', models.TextField(blank=True, null=True)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.survey')),
            ],
        ),
    ]
