# Generated by Django 3.2.7 on 2021-09-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0002_alter_surveyreports_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
